####main codes for microbial co-abundance network analysis (for questions, please contact Lianmin Chen, lianminchen@yeah.net)
#1.sparcc for network inference
#2.compute FDR for edges
#3.heterogeneity test
#4.cohort-specific edges selection
#5.resampling based approach to calculate FDR for heterogeneity test and cohort-specific edges
#6.partial correlation to check the confunding effect from covariates



###1.sparcc for network inference (Python)
python SparCC.py $INPUT_PATH --cor_file=$OUTPUT_PATH/real_cors_sparcc_sp.txt
python MakeBootstraps.py $INPUT_PATH -n $BOOT_ITER -t permutation_#.txt -p $OUTPUT_PATH/Resamplings/
# compute sparcc on permutated datasets
for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99
do
python SparCC.py $OUTPUT_PATH/Resamplings/permutation_$i.txt --cor_file=$OUTPUT_PATH/Bootstraps/sim_cor_$i.txt
done
# compute p-value from bootstraps
python PseudoPvals.py $OUTPUT_PATH/real_cors_sparcc_sp_fg.txt $OUTPUT_PATH/Bootstraps/sim_cor_#.txt $BOOT_ITER -o $OUTPUT_PATH/pvals_two_sided_sp_fg.txt -t two_sided


###2.compute FDR for network edges (R language)
data=data[order(abs(data$coefficient),decreasing = T),] #edge list with real coefficient and fake coefficient generated by 100x permutation by sparcc
data$fdr=NA
for(i in 1:nrow(data)){
  data$fdr[i]=(length(which(abs(data[,3:102])>=abs(data$coeffifient)[i]))/100)/i #3:102 columns represent fake coefficient generated by 100x permutation
}


###3.heterogeneity test (Cochran-Q test) on edges (R language)
##for co-abundance generated by sparcc (pearson)
library(meta)
TE=c(cor_lld,cor_500fg,cor_300ob,cor_ibd) #coefficient of certain edge in four cohorts
TEse=c(sqrt((1-cor_lld^2)/(1135-2)),sqrt((1-cor_500fg^2)/(450-2)),sqrt((1-cor_300ob^2)/(298-2)),sqrt((1-cor_ibd^2)/(496-2)))  #calculate se of coefficient
p_heterogeneity=metagen(TE,TEse)$pval.Q
##for co-abundance generated by spearman
TE=c(0.5*log((1+cor_lld)/(1-cor_lld)),0.5*log((1+cor_fg)/(1-cor_fg)),0.5*log((1+cor_ob)/(1-cor_ob)),0.5*log((1+cor_ibd)/(1-cor_ibd))) #transfer spearman coefficient to z-score (based on Park E. & Lee Y. J., Communications in Statistics-Simulation and Computation, 2001.)
TEse=c(1/sqrt(lld_n-3),1/sqrt(fg_n-3),1/sqrt(ob_n-3),1/sqrt(ibd_n-3)) #calculate se of z-score, lld_n represent non-zero pairs of certatin in lld (based on Park E. & Lee Y. J., Communications in Statistics-Simulation and Computation, 2001.)
p_heterogeneity=metagen(TE,TEse)$pval.Q
##for co-occurrence (chi-square) based on odds ratio
cor=log(((n_all_present_pair+0.5)*(n_all_absent_pair+0.5))/((n_present_absent_pair+0.5)*(n_absent_present_pair+0.5))) #calculate log odds ratio (plus 0.5 approach based on Valenzuela C. 1993, Rev. Med. Chil., PMID: 8085071)
TE=c(cor_lld,cor_500fg,cor_300ob,cor_ibd) #log odds ratio of certain edge in four cohorts
TEse=c(sqrt(1/(n_all_present_pair_lld+0.5)+1/(n_all_absent_pair_lld+0.5)+1/(n_present_absent_pair_lld+0.5)+1/(n_absent_present_pair_lld+0.5)),
       sqrt(1/(n_all_present_pair_fg+0.5)+1/(n_all_absent_pair_fg+0.5)+1/(n_present_absent_pair_fg+0.5)+1/(n_absent_present_pair_fg+0.5)),
       sqrt(1/(n_all_present_pair_ob+0.5)+1/(n_all_absent_pair_ob+0.5)+1/(n_present_absent_pair_ob+0.5)+1/(n_absent_present_pair_ob+0.5)),
       sqrt(1/(n_all_present_pair_ibd+0.5)+1/(n_all_absent_pair_ibd+0.5)+1/(n_present_absent_pair_ibd+0.5)+1/(n_absent_present_pair_ibd+0.5))) #calculate se of log odds ratio
p_heterogeneity=metagen(TE,TEse)$pval.Q


###4.cohort-specific edges selection based on correlation coefficient (R language)
cohort=c("LLD", "500FG", "300OB", "IBD")
IQR=quantile(TE,na.rm = T)[4]-quantile(TE,na.rm = T)[2] #TE represents coefficient/odds ratio of certain edge in four cohorts
if(length(which(TE<quantile(TE,na.rm = T)[2]-2*IQR))>0|length(which(TE>quantile(TE,na.rm = T)[4]+2*IQR)>0)){
  cohort_specific=cohort[c(which(TE<quantile(TE,na.rm = T)[2]-2*IQR),which(TE>quantile(TE,na.rm = T)[4]+2*IQR))]
} #edges without cohort specificity were recored as "-"


###5.resampling based (shuffel cohort labels) approach to calculate FDR for heterogeneity test and cohort-specific edge (R language)
lld=NULL
fg=NULL
ob=NULL
ibd=NULL
for(i in 0:99){
  permutation=sample(c(rep(1,1135),rep(2,450),rep(3,298),rep(4,496)),2379)
  lld_sp=sp[which(permutation==1),] #sp represents species matrix with 2379 samples from 4 cohorts
  write.table(lld_sp,file = paste("lld_sp_resampling",i,".txt",sep = "_"))
  fg_sp=sp[which(permutation==2),]
  write.table(fg_sp,file = paste("fg_sp_resampling",i,".txt",sep = "_"))
  ob_sp=sp[which(permutation==3),]
  write.table(ob_sp,file = paste("ob_sp_resampling",i,".txt",sep = "_"))
  ibd_sp=sp[which(permutation==4),]
  write.table(ibd_sp,file = paste("ibd_sp_resampling",i,".txt",sep = "_"))
}
##run sparcc on each resampled dataset (100x)--same as previous step 1 (Python)
##run heterogeneity test on each edge generated by resampled dataset (100x)--same as previous step 3 (R language)
##run cohort-specific edge selection on each edge generated by resampled dataset (100x)--same as previous step 4 (R language)
##calculate FDR for heterogeneity test and cohort-specific edge (R language)
data=data[order(data$hetero_p,decreasing = F),] #data represents real edge list with heterogeneity p value based on real coefficient/odds ratio (R language)
for(i in 1:nrow(data)){
  data$hetero_fdr_permutation[i]=(length(which(hetero_100_per<=all$hetero_p[i]))/100)/i #hetero_100_per is a matrix and contains heterogeneity p value generated by 100x resampling
  data$false_specific_n[i]=length(which(specific_100_per[i,]!="-")) #specific_100_per is a matrix and contains cohort-specific edges generated by 100x resampling
}


###6.partial correlation to check the confunding effect of covariates (use age and sex as an example) (R language)
library("corpcor")
cor=matrix(NA,4,4)
colnames(cor)=c("sp1","sp2","age","sex")
row.names(cor)=c("sp1","sp2","age","sex")
cor[1,1]=1
cor[2,2]=1
cor[3,3]=1
cor[4,4]=1
cor[2,1]=cor_sp1_sp2 #correlation coefficient of correlation between species1 and species2
cor[3,1]=cor.test(sp1,age,method = "pearson")$estimate #correlation coefficient of correlation between species1 and age
cor[4,1]=cor.test(sp1,sex,method = "pearson")$estimate #correlation coefficient of correlation between species1 and sex
cor[3,2]=cor.test(sp2,age,method = "pearson")$estimate #correlation coefficient of correlation between species2 and age
cor[4,2]=cor.test(sp2,sex,method = "pearson")$estimate #correlation coefficient of correlation between species2 and sex
cor[4,3]=cor.test(age,sex,method = "pearson")$estimate #correlation coefficient of correlation between age and sex
cor[upper.tri(cor)]=cor[lower.tri(cor)]
cor_partial_rm_age_sex=cor2pcor(cor)[2,1] #partial correlation coefficient of correlation between species1 and species2 after adjusting age and sex

